[build]
target = "i686-arkern.json" # set the target to the custom one

[unstable] # add the, essentially, std of nostd land
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.i686-arkern]
rustflags = "-C link-arg=-Tld.lld -C opt-level=1" # need the opt level >1 for the panic strings to be removed
                                                  # we don't need from the executable. and, of course, we need to include our
                                                  # linker script.